export const IpcChannels = {
  ListTranslations: 'bible:list-translations',
  GetActiveTranslation: 'bible:get-active-translation',
  SetActiveTranslation: 'bible:set-active-translation',
  GetTheme: 'app:get-theme',
  SetTheme: 'app:set-theme',
  FindBibleBooks: 'bible:find-books',
  GetChaptersForBook: 'bible:get-chapters',
  GetVersesForChapter: 'bible:get-verses',
  SearchBibleContent: 'bible:search-content',
  FindSongsByTitle: 'song:find-by-title',
  GetBlocksForSong: 'song:get-blocks',
  SearchSongContent: 'song:search-content',
  GetStagedItems: 'staged:get-all',
  StageItem: 'staged:add',
  UnstageItem: 'staged:remove',
  ReorderStagedItems: 'staged:reorder',
  GetLiveState: 'live:get',
  SetLiveState: 'live:set',
  SetOutputHidden: 'live:set-hidden',
  GetOutputStyles: 'styles:get',
  SetActiveStyle: 'styles:set-active',
  GetServerUrls: 'server:get-urls',
  PickOpenlpFiles: 'openlp:pick-files',
  ImportOpenlp: 'openlp:import',
  LiveStateChanged: 'live:changed',
} as const;
